project:
  type: website
  output-dir: docs
  render:
    - index.qmd # home page
    # - team.qmd # lab members
    # - lab-policies.qmd #code of conduct
    # - overview.qmd #research --> separate into sections
    # - env-on-phen.qmd
    # - adaptation-plasticity.qmd
    # - reproduction.qmd
    # - publications.qmd #teaching philosophy and courses taught
    # - lab-notebooks.qmd #online lab notebooks
    # - philosophy.qmd #teaching philosophy and courses taught
    # - RIE2.qmd
  
website:
  navbar:
    background: "#f4f1de"
    foreground: "#3d405b"
    pinned: true
    search: true
    tools:
      - icon: github
        href: https://github.com/yaaminiv
      - icon: share
        href: https://scholar.google.com/citations?user=x9WA39wAAAAJ&hl=en&oi=sra    
    right:
      - index.qmd
      - text: "about"
        menu:
          - team.qmd # people
          - lab-policies.qmd #code of conduct
          - resources.qmd #misc important things
      - text: "research"
        menu:
          - overview.qmd #overview of research themes
          - env-on-phen.qmd
          - adaptation-plasticity.qmd
          - reproduction.qmd
          - lab-notebooks.qmd #online lab notebooks
      - text: "teaching"
        menu:
          - philosophy.qmd #teaching philosophy and courses taught
          - RIE2.qmd
    page-navigation: true

format:
  html:
    theme: 
      - custom.scss
    format: revealjs
    css: styles.css