---
title: "Data science"
format: html
editor: visual
---

Despite their ecological importance, efforts to catalog protistan physiological abilities and trophic strategies lag behind those of their prokaryotic counterparts. The interpretation of large sequence datasets relies on the knowledge gleaned from culture-based transcriptome studies, new developments in genetic probing of microorganisms, and single-cell sequencing. It is imperative that we build reproducible pipelines and infrastructure to keep up with growing sequence information.

My two data science related goals are to (1) streamline the methods to link genotype and phenotype for environmentally-relevant microbial eukaryotes and (2) create an engaging environment to teach the next generation of scholars methods in computational approaches.

Contact me if you are interested in building up a 'data science community'.

## Reproducible pipelines & Bioinformatic tools

-   [EUKHeist](https://github.com/alexanderlabwhoi/EukHeist) & [preprint](https://www.biorxiv.org/content/10.1101/2021.07.25.453713v2)

-   [EUKulele](https://eukulele.readthedocs.io/en/latest/)

-   [Tag-sequencing work flows](https://github.com/shu251/tagseq-qiime2-snakemake)

-   [Extracting microbial eukaryotic information from metagenomes](https://github.com/shu251/Extract_microeukrRNA_from_metagenome)

-   [Analysing microbiome time-series](https://github.com/shu251/analyzing_microbiome_timeseries)
