---
title: "Lab notebooks"
editor: source
format: 
  html:
    toc: false
    toc-depth: 1
    toc-location: right
    number-sections: false
---

# Science becomes more equitable when information is accessible to all.

**All members of the MMEP Lab are required to keep electronic lab notebooks**. These lab notebooks act as resources for ourselves and others. We encourage the use of lab notebooks to document methodological processes, roadblocks, troubleshooting, half-baked ideas, and fresh results.

*Note: Due to SCU restrictions on sharing Google Docs, electronic lab notebooks hosted on Google Docs are not open access by default. If interested in viewing a lab notebook hosted on Google Docs, please submit a request for access on the document itself*

## Notebooks of current lab members

-   Dr. Yaamini R. Venkataraman: [yaaminiv.github.io](yaaminiv.github.io)
-   [Mikaela Bruno](https://docs.google.com/document/d/156p6lpch1gTSDPrkZHLP7HjBWkRur8-CPiNjss4SXTI/edit?tab=t.tv39a61tolyh#heading=h.35smbuej444m)
-   [Sasha Darknell-Brown](https://docs.google.com/document/d/1J422olLn7dHSSQc1bTKbC9LEUlelEH18MK-CrD1juT4/edit?tab=t.mqbehiak27x1)
-   [Clara Gray](https://docs.google.com/document/d/1KMPvsBltbcZBUgqUax1JXUHqDX8W9q23A0sm0T9ZmUA/edit?pli=1&tab=t.wipg68ddo7vc#heading=h.35smbuej444m)
-   [Jasmine Fong](https://docs.google.com/document/d/1wN_iivSvqCWL5rO3pwCrz-ZIHvlRv5piEsKXmv2jw5Y/edit?tab=t.tv39a61tolyh#heading=h.35smbuej444m)
-   [Emma Johansen](https://docs.google.com/document/d/1K6tJxHl-_tQnDi9zIDhY1sxgv70URRak4c_z2gCGD40/edit?pli=1&tab=t.2iv11di2nhdb#heading=h.npbng7wbtxob)
-   [Noemi Torres](https://docs.google.com/document/d/1cjhsooxLtzIYtettOJaJI_uJA0fzRZ34HZ8z5A2nfPQ/edit?tab=t.tv39a61tolyh#heading=h.35smbuej444m)

## Alumni notebooks

-   [Ashray Bangalore](https://docs.google.com/document/d/1-MuZuypVnc0nUEtyiGRPUvGrs4foERNqExVAmtFQPqs/edit?tab=t.tv39a61tolyh#heading=h.35smbuej444m)

## Resources

Below are some best practices about keeping a lab notebook and open science generally.

-   [Roberts Lab at University of Washington](https://robertslab.github.io/resources/Lab-Notebooks/)
-   [Columbia University: Good Laboratory Notebook Practices](https://research.columbia.edu/sites/default/files/content/RCT%20content/ReaDI%20Program/tutorial_LabNotebook_V9.pdf)
-   [Science: How to keep a lab notebook](https://www.science.org/content/article/how-keep-lab-notebook)
-   [NIH: Keeping an Electronic Lab Notebook](https://oir.nih.gov/system/files/media/file/2024-07/best_practices-keeping_eln-trainee_0.pdf)
-   [Center for Open Science](https://www.cos.io/open-science)
-   [UNESCO: Open science: Making sciecne more accessible, inclusive, and equitable for all](https://www.unesco.org/en/open-science)