---
title: "Teaching"
format: 
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    page-layout: full
editor: source
---

# Philosophy

**My goal as a teacher and mentor is to build a student’s ability to think critically about science and the social constructs that govern it**. Even if students do not pursue a career in science, technology, engineering, and mathematics (STEM), scientific literacy is crucial for understanding mechanisms behind social problems and sifting through false information.

- I know that developing scientific literacy skills can be a vulnerable process, so **I work with my students to create a supportive learning environment** where students feel they can practice skills and make mistakes in a safe and productive atmosphere.
- I implement flipped classrooms to improve scientific literacy, and **I have students facilitate flipped classrooms to build teaching and communication skills** in upper-division courses.
- **I develop and use inclusive teaching materials in my courses**, and incorporate diverse perspectives into my courses by involving early career STEM professionals

**I know my students are worth of compassion, care, and respect irrespective of their test scores, attendance record in my classroom, or other academic achievements**. I care about their growth as well-rounded members of society. If there's ever anything I can do to support you, I am here to help!

# Courses taught

An updated list of course offerings can be found at the [SCU Undergraduate Bulletin](https://www.scu.edu/appdata/pub/bulletin/undergraduate/2026-27/chapter-3-college-of-arts-and-sciences/biology.html).

| **Quarter** | **Course** | **Description** |
|------------------|---------------------|----------------------------------|
| Fall | BIOL 1C: Systems L&L | All biological phenomena are complex networks whose components comprise molecules, cells, organs, organisms, and ecosystems. The stability of these networks is maintained by important feedback and feedforward regulations but alterations affecting one of the components could affect the entire network. In this course, students will model biological systems (e.g., cellular signaling pathways, organismal body plans, human diseases, endangered natural habitats) in order to predict how they will respond and adapt to changes in components and environmental conditions. Students will also apply the process of science to collect, analyze, and interpret data across biological scales and communicate with the greater scientific community. |
| Winter 2026, Spring 2027 | BIOL 191: Project Lab | Course-based Undergraduate Research Experience (CURE) focusing on the eco-physiology of European green crabs. Students will learn animal husbandry, conduct live animal experiments with green crabs, and process samples for molecular analysis. Students will also practice formal and informal science communication skills. |
| Winter 2027 | BIOL 120: Animal Physiology L&L | This course examines contrasting strategies used by different animals to deal with variations in temperature, food, oxygen, and water, and highlights the diversity of physiological adaptations in major animal groups, especially those living in “extreme” habitats. |
| Spring 2026 | BIOL 6: The Oceans L&L | Examine the ocean environment from a physical, biological, ecological and evolutionary perspective. Our exploration of the marine environment will include an examination of human impacts on marine communities worldwide. The course is geared toward non-science majors and as such the learning goals of the course should be attainable to students from a wide variety of majors across the university. |
