---
title: "projects"
description: |
  Current & on-going research projects
output: 
  distill::distill_article:
    css: theme.css
    toc: true
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Deep-sea hydrothermal vents

Heterotrophic protists are ubiquitous in all aquatic ecosystems and represent an important ecological link by transferring organic carbon from primary producers to higher trophic levels. However, efforts to quantify protistan grazing pressure in the deep sea are rare. We quantified the predator-prey trophic interactions among protistan grazers and microbial prey at multiple sites of hydrothermal venting near the mid-ocean spreading center, Gorda Ridge, in the NE Pacific Ocean. A diverse assemblages of protistan species, determined from a genetic survey, was found to place greater predation pressure on the hydrothermal vent microbial population, relative to the surrounded seawater. This pattern was attributed to the higher concentration of chemosynthetic microorganisms and biological diversity localized to the hydrothermal vent environment.

## Axial Seamount

## Mid-Cayman Rise

## Gorda Ridge


# Time-series

The diversity of microbial eukaryotic trophic strategies makes them key players in marine food webs. Protists are single-celled microbial eukaryotes that play numerous ecological roles at the epicenter of marine food webs as primary producers, consumers, mixotrophs (mixed phototrophic and heterotrophic nutrition), and as partners in various mutualistic or parasitic associations. Within the diverse array of eukaryotic species, protist functional groups that exhibit heterotrophic nutrition or combined phototrophic and heterotrophic nutrition (mixotrophy) have been especially overlooked, especially from in situ studies.

# Data science

Despite their ecological importance, efforts to catalog protistan physiological abilities and trophic strategies lag behind those of their prokaryotic counterparts.