---
title: "Publications"
editor: visual
format: 
  html:
    toc: false
    toc-depth: 1
    toc-location: right
    number-sections: false
---

*Note: ^§^ = equal contribution, ^†^ = undergraduate author*

# *Pending*

Stay tuned!

# 2025

-   **Venkataraman YR**^§^, Huffmyer AS^§^. “Interrogating metabolic plasticity in marine organisms: A framework for best practices using metabolomic and lipidomic approaches.” Integrative and Comparative Biology. (2025). <https://doi.org/10.1093/icb/icaf138>

-   **Venkataraman YR**, Kelso JC^†^, Payne C^†^, Freitas HL^†^, Jasmine Kohler^†^, Tepolt CK. “Plasticity, not genetics, shapes individual responses to thermal stress in non-native populations of the European green crab (*Carcinus maenas*).” Integrative and Comparative Biology. (2025). <https://doi.org/10.1093/icb/icaf131>

-   Chaudhary VB, Kim SL, Medina M, Srivastava DS, Traylor-Knowles N, Brito-Millan M, Camargo-Cely Alejandra, Chatterjee S, Chen N, Chen Y, Gotanda K, Halsey S, Jack CN, McGuire RM, Miller CML, Moore A, Noh S, Ong T, Peralta AL, Puitiza A, Ramirez LN, Romero-Olivares AL, Pulido-Barriga MF, Sanchez K, Sit CY, Su C, Vazquez-Cardona J, **Venkataraman YR**, Werner CM, Khadempour L. “Racial Affinity Groups in STEM.” Science. (2024). <https://doi.org/10.1126/science.adq4733>

# 2024

-   Aluru N, **Venkataraman YR**, Murray CS, DePascuale V. “Gene expression and DNA methylation changes in response to hypoxia in toxicant-adapted Atlantic killifish (*Fundulus heteroclitus*).” Biology Open. (2024). <https://doi.org/10.1242/bio.061801>

-   **Venkataraman YR**, Huffmyer AS, White SJ, Downey-Wall A, Ashey J, Becker DM, Bengtsson Z, Putnam HM, Strand E, Rodriguez-Casariego JA, Wanamaker SA, Lotterhos KE, Roberts SB. “DNA methylation correlates with transcriptional noise in response to elevated pCO2 in the eastern oyster (*Crassostrea virginica*).” Ecological Epigenetics. (2024). <https://doi.org/10.1093/eep/dvae018>

# 2023

-   **Venkataraman YR**^§^, Shore A^§^, Dayal S^†^, Lee J, Salimi MA, Crandall G, Loeher MM, Stoops M, Swanger M^†^, Eisenlord MEE, Van Alstyne KL, Fast MD, Burge CA, Groner ML, “Characterizing host-pathogen interactions between *Zostera marina* and *Labyrinthula zosterae*.” Frontiers in Marine Science. (2023). <https://doi.org/10.3389/fmars.2023.1152647>

# 2022

-   Padilla-Gamiño J^§^, Alma L^§^, Spencer LH^§^, **Venkataraman YR**^§^, Wessler L^§^, “Ocean acidification does not overlook sex: Review of understudied effects and implications of low pH on marine invertebrate sexual reproduction.” Frontiers in Marine Science. (2022). <https://doi.org/10.3389/fmars.2022.977754>

-   **Venkataraman YR**, White SJ, Roberts SB, “Differential DNA methylation in Pacific oyster reproductive tissue associated with ocean acidification.” BMC Genomics. (2022). <https://doi.org/10.1186/s12864-022-08781-5>

-   Wanamaker SA^§^, **Venkataraman YR**^§^, Gavery M, Roberts SB, Bhattacharya D, Downey-Wall AM, Eirin-Lopez JM, Johnson KM, Lotterhos KE, Puritz JM, Putnam HM, “Invertebrate methylomes provide insight into mechanisms of environmental tolerance and reveal methodological biases.” Molecular Ecology Resources. (2022) <https://doi.org/10.1111/1755-0998.13542>

# 2020

-   Downey-Wall AM, Cameron L, Ford B, McNally, E, **Venkataraman YR**, Roberts SB, Ries J, Lotterhos KE, “Ocean acidification induces subtle shifts in gene expression and DNA methylation in mantle tissue of the eastern oyster (*Crassostrea virginica*).” Frontiers Marine Science. (2020). <https://doi.org/10.3389/fmars.2020.566419>

-   **Venkataraman YR**, Downey-Wall AM, Ries J, Westfield I, White S, Roberts SB, Lotterhos KE, “General DNA methylation patterns and environmentally-induced differential methylation in the eastern oyster (*Crassostrea virginica*).” Frontiers in Marine Science. 7:225 (2020). <https://doi.org/10.3389/fmars.2020.00225>

# 2019

-   **Venkataraman YR**, Spencer LH, Roberts S. “Larval response to parental low pH exposure in Pacific oysters (*Crassostrea gigas*).” Journal of Shellfish Research. 38(3):743-750 (2019). <https://doi.org/10.2983/035.038.0325>

-   Spencer LH, **Venkataraman YR**, Crim R, Ryan S, Horwith M, Roberts SB, “Carry-over effects of temperature and pCO~2~ across multiple Olympia oyster populations.” Ecological Applications. 30(3):02060 (2019). <https://doi.org/10.1002/eap.2060>

-   Foley HB, Sun PY, Ramirez R, So BK, **Venkataraman YR**, Nixon EN, Davies KJA, Edmands S. “Sex-specific stress tolerance, proteolysis, and lifespan in the invertebrate *Tigriopus californicus*.” Experimental Gerontology. 119:46-56 (2019). <https://doi.org/10.1016/j.exger.2019.02.006>

-   Spencer LH, Horwith M, Lowe AT, **Venkataraman YR**, Timmins-Schiffman E, Nunn BL, Roberts SB. “Pacific geoduck (*Panopea generosa*) resilience to natural pH variation.” Comparative Biochemistry and Physiology Part D: Genomics and Proteomics 30:91-101 (2019). <https://doi.org/10.1016/j.cbd.2019.01.010>

-   **Venkataraman YR**, Timmins-Schiffman E, Horwith M, Lowe AT, Nunn BL, Vadopalas B, Spencer LH, Roberts SB. “Characterization of proteomic response to natural environmental differences in the Pacific oyster (*Crassostrea gigas*).” Marine Ecology Progress Series. 610:65-81 (2019). <https://doi.org/10.3354/meps12858>

# Community resources

-   Manafzadeh A^§^, Navon D^§^, **Venkataraman YR**^§^, Millward JK, Khan F, Ashiru O (2024). DNA Genotype-phenotype associations: What are they and how do they relate to broader society? Resources for Inclusive Evolution Education, QUBES Educational Resources. <https://doi.org/10.25334/MWZF-D038>

-   **Venkataraman YR**, Greiner-Ferris K, White SJ, Roberts SB (2024). DNA Methylation Assessment. MarineOmics. <https://marineomics.github.io/FUN_02_DNA_methylation.html>
