---
title: "publications"
description:
output: 
  distill::distill_article:
    css: theme.css
    toc: true
    toc_depth: 3
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.align = "center")
```

# _pending_

* Alexander, H., Hu, S.K., Pachidaki, M, Krinos, A.I., Tully, B.J., Neely, C.J., & Reiter, T. Eukaryotic genomes from a global metagenomic dataset illuminate trophic modes and biogeography of ocean plankton. (In Review). [bioRxiv: 2021.07.25.453713](https://www.biorxiv.org/content/10.1101/2021.07.25.453713v1)

* Neely, C.J., Hu, S.K., Alexander, H., Tully, B.J. The high-throughput gene prediction of more than 1,700 eukaryote genomes using the software package EukMetaSanity. (In Review) [bioRxiv: 2021.07.25.453296](https://www.biorxiv.org/content/10.1101/2021.07.25.453296v1) 

* Beckett, S.J., Demory, D., Coenen, A.R., Casey, J.R., Follet, C.L., Dugenne, M., Connell, P., Carlson, Michael C.G., Hu, S. K., et al. Nonlinear feedbacks and diel population dynamics of cyanobacteria, viruses, and grazers in the North Paciﬁc Subtropical Gyre. (In Review). [bioRxiv](Nonlinear feedbacks and diel population dynamics of cyanobacteria, viruses, and grazers in the North Paciﬁc Subtropical Gyre)

* Hu, S.K., Alexander, H., Liu, Z., Heidelberg, K.B., Dyhrman, S. & Caron, D.A. Distinct transcriptional signatures of the protistan community at the SPOT and ALOHA ocean time-series stations. (In Review).

# 2022

* Hammond, S.W,, Lodolo, L., Hu, S.K., & Pasulka, A.L. (_In Press_) Methodological ‘lenses’ influence the characterization of phytoplankton dynamics in a coastal upwelling ecosystem. Environmental Microbiology Reports

* Ollison, G.A., Hu, S.K., Hopper, J.V., Stewart, B.P., Smith, J., Beatty, J.L., et al. (2022) Daily dynamics of contrasting spring algal blooms in Santa Monica Bay (central Southern California Bight). Environmental Microbiology 1462-2920.16137.

* Cohen, N.R., Alexander, H., Krinos, A.I., Hu, S.K., and Lampe, R.H. (2022) Marine Microeukaryote Metatranscriptomics: Sample Processing and Bioinformatic Workflow Recommendations for Ecological Applications. Front Mar Sci 9: 867007. [link](https://www.frontiersin.org/articles/10.3389/fmars.2022.867007/full)


# 2021

* Tully, B.J., Buongiorno, J., Cohen, A.B., Cram, J.A., Garber, A.I., Hu, S.K., et al.. The Bioinformatics Virtual Coordination Network: an open-source and interactive learning environment. (2021) Frontiers in Education: STEM Education.

* Ollison G., Hu, S.K., Mesrop, L.Y., Delong, E. & Caron, D. A. (2021) Come Rain or Shine: Depth Not Season Shapes the Protistan Community at Station ALOHA in the North Pacific Subtropical Gyre. Deep-Sea Research Part II. [link](https://www.sciencedirect.com/science/article/pii/S0967063721000339)

* Hu, S.K., Herrera, E.L., Smith, A.R., Pachiadaki, M.G., Edgcomb, V.P., Sylva, S.P., Chan E.W., Seewald, J.S., German, C.R., & Huber, J.A. (2021) Protistan grazing impacts microbial communities and carbon cycling in the deep-sea hydrothermal vent environment. Proc Natl Acad Sci USA [link](https://www.pnas.org/content/118/29/e2102674118) [code](https://shu251.github.io/protist-gordaridge-2021/)

# 2020

* Coesel, S.N., Durham, B.P., Groussman, R.D., Hu, S.K., Caron, D.A., Morales, R.L., et al. (2021) Diel transcriptional oscillations of light-sensitive regulatory elements in open-ocean eukaryotic plankton communities. Proc Natl Acad Sci USA 118: 12. [link](https://www.pnas.org/content/118/6/e2011038118)

* Krinos, A., Hu, S., Cohen, N., and Alexander, H. (2021) EUKulele: Taxonomic annotation of the unsung eukaryotic microbes. JOSS 6: 2817. [link](https://joss.theoj.org/papers/10.21105/joss.02817)

* Goordial, J., Hu, S., & Tully, B. (2020). C-DEBI NextGen 2019 Early Career perspective on ‘What’s Next?’: Upcoming Challenges and Opportunities. DOI: 10.31219/osf.io/7xkpq [link](https://www.darkenergybiosphere.org/publication/c-debi-nextgen-2019-early-career-perspective-on-whats-next-upcoming-challenges-and-opportunities/)

* Coenen, A.R., Hu, S.K., Luo, E., Muratore, D., and Weitz, J.S. (2020) A Primer for Microbiome Time-Series Analysis. Front Genet 11: 310. [link](https://www.frontiersin.org/articles/10.3389/fgene.2020.00310/full)

* Lim, Darlene S.S., Raineault, N.A., Brier, J.A., Chan, E., Chernov, J., Cohen, T., Deans, M., Garcia, A., German, C. R., Hauer, M., Hu, S.K., Huber, J.A., Kane, R., Kobs Nawotniak, S., Lees, D., Lowe, J., Lubetkin, M., Marsh, L., Milesi, V., Miller, M., Miramalek, Z., Saunders, M., Sharif, K., Shields, A., Shock, E., Smith, A.R., and Sylva, S. (2020), SUBSEA 2019 Expedition to the Gorda Ridge, Oceanography 33(1), Supplement Pages 36 – 37.

# 2019
* Boeuf, D., Edwards, B.R., Eppley, J.M., Hu, S.K., Poff, K.E., Romano, A.E., et al. (2019) Biological composition and microbial dynamics of sinking particulate organic matter at abyssal depths in the oligotrophic open ocean. Proc Natl Acad Sci USA 11824–11832. [link](https://www.pnas.org/content/116/24/11824)

* Liu, Z., Mesrop, L.Y., Hu, S.K., and Caron, D.A. (2019) Transcriptome of _Thalassicolla nucleata_ Holobiont Reveals Details of a Radiolarian Symbiotic Relationship. Front Mar Sci 6: 284. [link](https://www.frontiersin.org/articles/10.3389/fmars.2019.00284/full)

* Pasulka, A., Hu, S.K., Countway, P.D., Coyne, K.J., Cary, S.C., Heidelberg, K.B., and Caron, D.A. (2019) SSU rRNA Gene Sequencing Survey of Benthic Microbial Eukaryotes from Guaymas Basin Hydrothermal Vent. Journal of Eukaryotic Microbiology jeu.12711.[link](https://onlinelibrary.wiley.com/doi/10.1111/jeu.12711)

* Caron, D.A. and Hu, S.K. (2019) Are We Overestimating Protistan Diversity in Nature? Trends in Microbiology 27: 197–205.[link](https://www.sciencedirect.com/science/article/abs/pii/S0966842X18302324?via%3Dihub)

# 2018
* Hu, S.K., Liu, Z., Alexander, H., Campbell, V., Connell, P.E., Dyhrman, S.T., et al. (2018) Shifting metabolic priorities among key protistan taxa within and below the euphotic zone: Depth-related protistan metatranscriptomes. Environ Microbiol 20: 2865–2879. [link](https://sfamjournals.onlinelibrary.wiley.com/doi/abs/10.1111/1462-2920.14259)

* Hu, S.K., Paige E. Connell, Mesrop, L.Y., and Caron, D.A. (2018) A Hard Day’s Night: Diel Shifts in Microbial Eukaryotic Activity in the North Pacific Subtropical Gyre. Front Mar Sci 5:251. [link](https://dornsife.usc.edu/assets/sites/378/docs/Caron_pdfs/2018_Hu_etal_FrontiersMarineScience.pdf)

# 2017
* Liu, Z., Hu, S.K., Campbell, V., Tatters, A.O., Heidelberg, K.B., and Caron, D.A. (2017) Single-cell transcriptomics of small microbial eukaryotes: limitations and potential. The ISME Journal 11: 1282–1285.

* Connell, P.E., Campbell, V., Gellene, A.G., Hu, S.K., and Caron, D.A. (2017) Planktonic food web structure at a coastal time-series site: II. Spatiotemporal variability of microbial trophic activities. Deep Sea Res Part I Oceanogr Res Pap 121: 210–223.

# 2016
* Hu, S.K., Campbell, V., Connell, P., Gellene, A.G., Liu, Z., Terrado, R., and Caron, D.A. (2016) Protistan diversity and activity inferred from RNA and DNA at a coastal ocean site in the eastern North Pacific. FEMS Microbiol Ecol fiw050. [link](https://academic.oup.com/femsec/article/92/4/fiw050/2197988)

# 2015 
* Hu, S.K., Liu, Z., Lie, A.A.Y., Countway, P.D., Kim, D.Y., Jones, A.C., et al. (2015) Estimating Protistan Diversity Using High-Throughput Sequencing. Journal of Eukaryotic Microbiology 62: 688–693.

* Lie, A.A.Y., Liu, Z., Hu, S.K., Jones, A.C., Kim, D.Y., Countway, P.D., et al. (2014) Investigating Microbial Eukaryotic Diversity from a Global Census: Insights from a Comparison of Pyrotag and Full-Length Sequences of 18S rRNA Genes. Applied and Environmental Microbiology 80: 4363–4373.