---
title: "General resources"
editor: source
format: 
  html:
    toc: true
    toc-depth: 4
    toc-location: left
    number-sections: false
---

# An ever-growing list of links.

Please [email Dr. Venkataraman](mailto:yvenkataraman@scu.edu) if there's something you'd like to add!

## SCU-specific

- [SCU Biology](https://www.scu.edu/cas/biology/)
- [Research at SCU Biology](https://www.scu.edu/cas/biology/beyond-the-classroom/research/)
- [SCU Library](https://www.scu.edu/library/)
- [SCU Office of Accessible Education](https://www.scu.edu/oae/)
- [Single Portal for Undergraduate Research (SPUR)](https://www.scu.edu/provost/research/student-funding-opportunities/scuspur/): Single application portal for several SCU summer research fellowships
- [REAL Program](https://www.scu.edu/real/): Stipends for College of Arts and Sciences student research, internships, or creative projects
- [DeNardo Science Scholars](https://www.scu.edu/denardo/science-scholars/): support undergarduate reserach during the academic year and summer
- [De Novo Fellowship](https://www.scu.edu/cas/beyond-the-classroom/denovo/): Fellowship for students with outstanding academic records who may have overcome financial challenges and/or may not have had field-specific role models.
- [The Multicultural Center](https://www.mccscu.com)
- [Dean of Students Office](https://www.scu.edu/dso/)
- [Basic Needs Program](https://www.scu.edu/dso/basicneeds/): Bronco Food Pantry, Housing and Utility Assistance, Technology Support, Transportation Support and Student Life Fund links, among other things
- [The Wellness Center](https://www.scu.edu/wellness/)
- [Counseling and Psychological Services](https://www.scu.edu/bewell/caps/)
- [Office of Equal Opportunity and Title IX](https://www.scu.edu/title-ix/)
- [Office for Diversity and Inclusion (ODI)](https://www.scu.edu/diversity/)
- [Office for Multicultural Learning (OML)](https://www.scu.edu/oml/)
- [Rainbow Resource Center (RRC)](https://www.scu.edu/oml/rrc/)

## General resources

- [Biology Summer Internships outside of SCU](https://docs.google.com/document/d/14F9l_oUP43x4HRKykG8rgkW2Ts4oF-w5mrDWxmUk4sI/edit?tab=t.0)
- [Undergraduate guide from Roberts Lab at University of Washington](https://faculty.washington.edu/sr320/undergraduate_guide.html): Comprehensive resource on conducting undergraduate research, from contacting faculty and determining what kinds of opportunities are right for you, to asking for letters of recommendation. Links are UW-specific, but there is good general advice.
- [Resources page of the Inclusive Conservation Lab at UBC](https://www.inclusiveconservationlab.com/resources): Note that this lab is based in Canada, some several resources are Canada or UBC-specific
- [How to apply for graduate student positions](https://sites.google.com/view/apply-academic-positions/graduate-student?authuser=0): compiled by Dr. Lily Khadempour, useful for those interested in pursuing graduate school
- [Fifteen Questions to Ask Before Attending Graduate School](https://esajournals.onlinelibrary.wiley.com/doi/full/10.1002/bes2.70047?ref=scienceforeveryone.science): A good resources from the Ecological Society of America

## Equity, diversity, inclusion, and belonging

- [#STEMforBLM Resource List](https://docs.google.com/document/d/1f9L5-NiqDhEDiAmysDDXx5KBXeTAT5Z7vPfb0e3WSXM/edit?fbclid=IwAR3WPPeZPhjFBlMACpNvam_uX7a6PRttHR5QYGwOocQMJBIz6ZX4BOIfLQ4&tab=t.0#heading=h.fbpn1x31jlk5): Justice-oriented resources inside and outside academia
- [Revisiting "Beyond Territorial Acknolwedgements"](https://apihtawikosisan.com/2024/11/revisiting-beyond-territorial-acknowledgments/): Discussion on land/territorial acknowledgements and what can exist beyond an acknolwedgement
- [Center for the Improvement of Mentored Experiences in Research (CIMER) Trainings](https://cimerproject.org/training/): Trainings for mentors and mentees
- [Resources for Inclusive Evolution Education (RIE2)](https://qubeshub.org/community/groups/rie2): Collection of resources and community-developed teaching modules

### Affinity groups

- [Women of Color & Non-Binary People of Color in Ecology & Evolutionary Biology (WOC in EEB)](https://www.wocineeb.org/index.html)
- [WOC in EEB Mentoring Program](https://sites.google.com/view/wocineeb-mentoring/home): A mentoring program run by WOC in EEB. The page also has resources on effective mentoring.
- [Minorities in Shark Sciences (MISS)](https://www.misselasmo.org)
- [Black in Marine Science (BIMS)](https://www.blackinmarinescience.org)
- [Black Women in Ecology, Evolution, and Marine Science](https://www.bweems.org)

### Recommended reading

#### Articles

- [Black scientists call out racism in their institutions](https://www.theverge.com/21286924/science-racism-strike-stem-black-lives-matter-protests)
- [The science divide: Why do Latino and black students leave STEM majors at higher rates?](https://www.washingtonpost.com/local/education/the-science-divide-why-do-latino-and-black-students-leave-stem-majors-at-higher-rates/2019/05/03/e386d318-4b32-11e9-93d0-64dbcf38ba41_story.html?pwapi_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyZWFzb24iOiJnaWZ0IiwibmJmIjoxNzAyMzU3MjAwLCJpc3MiOiJzdWJzY3JpcHRpb25zIiwiZXhwIjoxNzAzNzM5NTk5LCJpYXQiOjE3MDIzNTcyMDAsImp0aSI6IjUyMDlhOTMzLWFkNTQtNDlkOC1iZjI2LTlkZTc1MjRiMGNhOCIsInVybCI6Imh0dHBzOi8vd3d3Lndhc2hpbmd0b25wb3N0LmNvbS9sb2NhbC9lZHVjYXRpb24vdGhlLXNjaWVuY2UtZGl2aWRlLXdoeS1kby1sYXRpbm8tYW5kLWJsYWNrLXN0dWRlbnRzLWxlYXZlLXN0ZW0tbWFqb3JzLWF0LWhpZ2hlci1yYXRlcy8yMDE5LzA1LzAzL2UzODZkMzE4LTRiMzItMTFlOS05M2QwLTY0ZGJjZjM4YmE0MV9zdG9yeS5odG1sIn0.YasZvKKmtKNI0PStBu27q56SmXxUmy5Z8gRAmK0UGss)
- [Facilitating Critical Conversations With Students](https://www.learningforjustice.org/sites/default/files/2019-12/TT-Lets-Talk-December-2019.pdf)

#### Books

Various books ranging from environmental justice and climate solutions to eugenics and dark academia.

- Fresh Banana Leaves by Jessica Hernandez, Ph.D
- We Will Be Jaguars by Nemonte Nenquimo
- Our History Is The Future by Nick Estes
- Why Fish Don't Exist by Lulu Miller
- Superior: The Return of Race to Science by Angela Saini
- The New Jim Crow by Michelle Alexander
- So You Wanna Talk About Race by Ijeoma Oluo
- Mediocre by Ijeoma Oluo
- Be A Revolution by Ijeoma Oluo
- The Immortal Life of Henrietta Lacks by Rebecca Skloot
- All We Can Save edited by Dr. Ayana Elizabeth Johnson and Dr. Katharine Wilkinson
- What If We Get It Right? Visions of Climate Futures by Dr. Ayana Elizabeth Johnson
- Consumed by Aja Barber
- Lessons from Plants by Dr. Beronda Montgomery
- The Disordered Cosmos by Chanda Prescod-Weinstein
- Disability Visability by Alice Wong
- Race after Technology by Ruha Benjamin
- Imagination: A Manifesto by Ruha Benjamin
- Growing Papaya Trees by Jessica Hernandez, Ph.D
- Read This When Things Fall Apart by Kelly Hayes
- Reconsidering Reparations by Olúfẹ́mi O. Táíwò
- Elite Capture by Olúfẹ́mi O. Táíwò
